language: php

sudo: false

dist: precise

php:
  - '5.6'
  - '7.0'
  - '7.1'

git:
  depth: 5

cache:
  directories:
    - $HOME/.composer/cache

addons:
  apt:
    packages:
      - parallel

before_script:
    - composer install